### ISSUE TITLE
Could you provide a way to calculate ST-MJE?

### ISSUE THREAD

**Issue by TheVirtuoso7** [amathislab/HOISDF#13]
Could you provide a way to calculate (Scale-Translation aligned Mean Joint Error)ST-MJE? I checked the references [58] and found nothing about ST-MJE, it was all about MP-JPE. Maybe it's because I'm not capable enough. Can you provide the code or formula for its calculation?  I would appreciate it.

**Comment by HaozheQi** [comment]
Hi,
Thank you for your interest in our work. We only report the ST-MJE metric on the HO3Dv2 dataset, which is obtained by submitting the predictions to the [official website](https://codalab.lisn.upsaclay.fr/competitions/4318#learn_the_details-evaluation). Therefore, we did not include the ST-MJE implementation in the codebase. 

However, you can find the official implementation of ST-MJE from the [HO3D repository](https://github.com/shreyashampali/ho3d/blob/master/eval.py#L201).

**Comment by TheVirtuoso7** [comment]
> Hi, Thank you for your interest in our work. We only report the ST-MJE metric on the HO3Dv2 dataset, which is obtained by submitting the predictions to the [official website](https://codalab.lisn.upsaclay.fr/competitions/4318#learn_the_details-evaluation). Therefore, we did not include the ST-MJE implementation in the codebase.
> 
> However, you can find the official implementation of ST-MJE from the [HO3D repository](https://github.com/shreyashampali/ho3d/blob/master/eval.py#L201).

I see. Thank you for your reply, I sincerely appreciate your assistance.
