### ISSUE TITLE
HOISDF with the rendered images

### ISSUE THREAD

**Issue by liangshenglei** [amathislab/HOISDF#4]
An excellent paper, and I am also very interested in it. But I noticed that you haven't released the rendering dataset yet. Do you have any plans to release it? Thank you.

**Comment by liangshenglei** [comment]
emmm,Can you also provide the processed SDF file?

**Comment by AlexEMG** [comment]
The data is very big, and we are currently asking for an increased quota on Zenodo to host them. Stay tuned.

**Comment by HaozheQi** [comment]
Hello, we are glad to announce that we have uploaded the rendering data and also the processed SDF files. You can find them in the readme. Feel free to reach out if you have any other questions :)
