### ISSUE TITLE
Problems in data processing.

### ISSUE THREAD

**Issue by TheVirtuoso7** [amathislab/HOISDF#6]
Hello！
I appreciate your outstanding work. 
There is a couple of inquiries that confuse  me a lot, could you give me some advice?
Firstly, the link to the processed dataset you provided is currently invalid. Could you restore access if feasible? 
Secondly, when we follow the AlignSDF method, an error occurs in dexyb.py during its runtime: self.sdf_index_list.append(raw_sdf_index[sdf_list.index(sdf_file_name)]) ValueError: 'id_9' is not in list. Do you have any idea about the cause? Is there an issue with the way I handle the data? Could you please respond? 
Thank you once again for your efforts.

**Comment by HaozheQi** [comment]
Hi, we have successfully uploaded the processed SDF files and now you can get access to them. 

Regarding the problem you mentioned, I think it's because you didn't generate the corresponding SDF file.

**Comment by AlexEMG** [comment]
Please note, we updated the dataset instructions accordingly: https://github.com/amathislab/HOISDF/blob/main/README.md#dataset-setup

**Comment by TheVirtuoso7** [comment]
Thank you for the excellent work!
