### ISSUE TITLE
Where can I get hand-object interaction information?

### ISSUE THREAD

**Issue by lpy523** [amathislab/HOISDF#9]
Thank you for your excellent work!
I have a naive question, which part of the HOISDF model can get the hand-object interaction information (e.g. relative position, relative distance), and where exactly in the code? 
Thank you very much!

**Comment by HaozheQi** [comment]
Hi, thank you for your interest. Our model directly predict the object 6D pose relative to the hand root position. You can find how to generate the GT relative position from [here](https://github.com/amathislab/HOISDF/blob/main/data/dexycb.py#L625).
